### ISSUE TITLE
All characters do not unlock

### ISSUE THREAD

**Issue by simon1245678910** [kyeondiscord/crossy-road-hack#1]
Hey, first I just want to say this is amazing, everything works! I've been playing around with the hack pressing the lock and unlock buttons, but for some reason when I press the unlock button only 52 characters (including the hidden) out of the 160 are unlocked. If you could fix this it would be greatly appreciated.

**Comment by KyeOnDiscord** [comment]
Crossy road has some skins in different ways so I'm not sure if I can unlock those however I can look into it.

**Comment by simon1245678910** [comment]
> Crossy road has some skins in different ways so I'm not sure if I can unlock those however I can look into it.

thanks
